artist_names = ["Screwtape",
"3 Speed",
"Essential Bounce",
"Let's Dance Tonight",
"Purest Form",
"The Birdwatcher",
"Cadaveric Crematorium",
"John Alder",
"Mike Hammer",
"Shands Superior Jubilee Singers",
"Mission Impossible",
"John Askey",
"Christopher van Kampen",
"Little Screaming Pilgrims",
"Mastretta",
"De Elite",
"Lady Luck & Jink Da Juvy",
"Ultra Violet",
"Canine",
"Ruby Vass",
"Physical Attraction",
"King Willy",
"Spud Murphy",
"Tommy Engel",
"Jason Phats",
"John Huss Moderate Combo",
"Noble Sissle",
"Mr Spring",
"Ridis",
"Sara Puljula",
"Daniel Guss",
"Deviate Damaen",
"Space Blaster",
"One Motion",
"Assym",
"James Perry & Co",
"Chong-Nee",
"Giovanni Coprario",
"365",
"The Insignificant",
"Ron Land",
"太陽とシスコムーン",
"Zigi",
"Cobblestone Jazz",
"Mlolothwa",
"Dale Juner",
"Bonnie Miller",
"Jr. James & The Late Guitar",
"Jesse Fortune",
"Christoph Bernhard Becker",
"Certain Distant Suns",
"Sammy Masters",
"Who Be Dat",
"Black Jazz Chronicles",
"Sixto Ferrer Lopez",
"Macho Cat Garage",
"Jason Suecof",
"Erhan Güleryüz",
"George Mraz"]